name: Generate Tag & Create Pull Request
on:
  workflow_dispatch:
    inputs:
      increaseVersion:
        description: '버전업 할 버전종류를 입력해주세요.'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: '이전 Tag 버전 조회'
        id: previoustag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) --abbrev=0)
          PREVIOUS_TAG=$(git describe --tags $(git rev-list --tags --skip=1 --max-count=1) --abbrev=0) || echo "No previous tag"
          echo "::set-output name=tag::$PREVIOUS_TAG"

      - name: '배포 버전 생성'
        id: currentVersion
        run: |
          IFS='.' read -ra array <<< ${{steps.previoustag.outputs.tag}}
          if [[ "${{ github.event.inputs.increaseVersion }}" == "major" ]]; then
            array[0]=$((array[0] + 1))
          elif [[ "${{ github.event.inputs.increaseVersion }}" == "minor" ]]; then
            array[1]=$((array[1] + 1))
          elif [[ "${{ github.event.inputs.increaseVersion }}" == "patch" ]]; then
            array[2]=$((array[2] + 1))
          else
          echo "Invalid version option selected"
          fi
          
          echo "::set-output name=version::${array[0]}.${array[1]}.${array[2]}"

      - name: Release Branch 생성
        run: |
          git config --local user.email "rhtld123@gmail.com"
          git config --local user.name "rhtld123"
          
          git checkout master
          git pull
          git fetch origin stage:stage
          git checkout -b release/${{steps.currentVersion.outputs.version}}
          git merge --no-ff stage
          git push origin release/${{steps.currentVersion.outputs.version}}

      - name: Change Log 받아오기
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOKEN }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.TOKEN }}
          title: "v${{steps.currentVersion.outputs.version}} 배포"
          body: "${{ steps.tag_version.outputs.changelog }}"
          branch: "release/${{steps.currentVersion.outputs.version}}"
          base: "master"