name: Release
on:
  pull_request:
    branches:
      - master
    types: [ closed ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9

      - name: 버전 정보 추출(from Branch Name)
        run: echo "TAG=$(echo '${{ steps.branch-name.outputs.current_branch }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV

      - name: Fetch all commits
        run: git fetch --depth=1 origin +refs/heads/master

      - name: Get the commit range
        id: commitRange
        run: echo "::set-output name=range::$(git rev-parse origin/master)..HEAD"

      - name: Get the change logs
        id: changeLogs
        run: |
          RANGE="${{ steps.commitRange.outputs.range }}"
          CHANGELOGS=$(git log --pretty=format:"- %s" $RANGE)
          echo "::set-output name=changelogs::$CHANGELOGS"

      - name: Release & Tag 생성
        if: github.event.pull_request.merged == true
        uses: ncipollo/release-action@v1 
        with:
          tag: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          body: ${{ steps.changeLogs.outputs.changelogs }}